canonical:
  - Particulars
  - Revenue from Operations
  - Other Income
  - Total Income
  - EBITDA
  - Depreciation
  - EBIT
  - Finance Costs
  - Profit Before Tax
  - Tax Expense
  - Profit After Tax
  - Share Capital
  - Reserves & Surplus
  - Net Worth
  - Total Assets
  - Total Liabilities
