phrases:
  - as on
  - for the year ended
  - for the quarter ended
  - nine months ended
  - half year ended
tokens:
  - ended
  - year
  - quarter
  - months
date_patterns:
  - "(\\d{1,2})\\s*(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\\s*(19|20)\\d{2}"
  - "(19|20)\\d{2}"
  - "(\\d{1,2})[-/](\\d{1,2})[-/](19|20)\\d{2}"
